version: '3'

services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - bugtracker_postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

volumes:
  bugtracker_postgres_data:
