# Generated by Django 3.0.8 on 2020-08-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_viewed_project_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_viewed_project_pk',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
