# Generated by Django 3.0.8 on 2020-08-20 20:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200813_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
