# Generated by Django 3.0.8 on 2020-08-20 20:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_notification_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notification_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
