# Generated by Django 3.0.8 on 2020-08-03 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_teammanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammanager',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Team'),
        ),
    ]
