# Generated by Django 3.0.8 on 2020-08-03 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0007_team_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='managers',
            field=models.ManyToManyField(related_name='manager_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TeamManager',
        ),
    ]
