# Generated by Django 3.0.8 on 2020-08-14 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0014_auto_20200812_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='ticket_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
