# Generated by Django 3.0.8 on 2020-08-17 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0015_ticket_subscribers'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.Team')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracker_team_members',
            },
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams', through='tracker.TeamMembership', to=settings.AUTH_USER_MODEL),
        ),])
    ]
