# Generated by Django 3.0.8 on 2020-08-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_auto_20200817_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
    ]
