# Generated by Django 3.0.8 on 2020-08-17 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_auto_20200817_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='tracker.Team'),
        ),
    ]
