# Generated by Django 3.0.8 on 2020-08-18 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0024_auto_20200817_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='project_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
