# Generated by Django 3.0.8 on 2020-08-19 17:57

import bug_tracker_v2.tracker.model_validators
import bug_tracker_v2.tracker.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_auto_20200819_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketfile',
            name='file',
            field=bug_tracker_v2.tracker.model_validators.ContentTypeRestrictedFileField(upload_to=bug_tracker_v2.tracker.models.ticket_file_upload_path),
        ),
    ]
