# Generated by Django 3.0.8 on 2020-08-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_auto_20200819_1357'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticketfile',
            unique_together={('ticket', 'title')},
        ),
    ]
