# Generated by Django 3.0.8 on 2020-08-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_auto_20200819_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvitation',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='teaminvitation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Declined')], default=1),
        ),
    ]
